project:
  type: book
  output-dir: docs

book:
  title: "CSC 303 Notes"
  author: "Homer White"
  date: today
  chapters:
    - index.qmd
    - 02-visualization-basics.qmd
    - 03-grammar-graphics.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




